// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22D_JwP7bLYyYEZNWkhbF1gty0JkYWhA',
    appId: '1:1097409182267:web:7bc9a2e3f4c9d5e6f7g8h9i0',
    messagingSenderId: '1097409182267',
    projectId: 'kitchen-manager-app-42ba8',
    authDomain: 'kitchen-manager-app-42ba8.firebaseapp.com',
    storageBucket: 'kitchen-manager-app-42ba8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA22D_JwP7bLYyYEZNWkhbF1gty0JkYWhA',
    appId: '1:1097409182267:android:285476aa7c9013c5cefa1e',
    messagingSenderId: '1097409182267',
    projectId: 'kitchen-manager-app-42ba8',
    storageBucket: 'kitchen-manager-app-42ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexampleKeyForIOSPlatform1234567890',
    appId: '1:1097409182267:ios:285476aa7c9013c5cefa1e',
    messagingSenderId: '1097409182267',
    projectId: 'kitchen-manager-app-42ba8',
    storageBucket: 'kitchen-manager-app-42ba8.firebasestorage.app',
    iosClientId: '1097409182267-example.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitchenManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexampleKeyForMacOSPlatform1234567890',
    appId: '1:1097409182267:macos:285476aa7c9013c5cefa1e',
    messagingSenderId: '1097409182267',
    projectId: 'kitchen-manager-app-42ba8',
    storageBucket: 'kitchen-manager-app-42ba8.firebasestorage.app',
    iosClientId: '1097409182267-example.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitchenManagerApp.macos',
  );
}
